# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 05:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    operations = [
    	#up and down in rails
    	#migrations.RunSQL("""ALTER TABLE auth_user DROP CONSTRAINT ck_nospecialchars_username """),
    	migrations.RunSQL("""ALTER TABLE auth_user ADD CONSTRAINT ck_nospecialchars_username
    	CHECK (username ~ '^[a-zA-Z0-9]*$'); """),
    ]
